kind: Secret
apiVersion: v1
metadata:
  name: credenciales-api-rest
data:
  basic-auth-pass: YXBpcmVzdGRlbW8=
  basic-auth-user: Y2NsaA==
  database-mongodb: dGVzdA==
  uri-mongodb: >-
    bW9uZ29kYitzcnY6Ly9EZW1vQXBpUmVzdENsaWVudGU6ODg1Q2I2ZXB3azNlQGNsdXN0ZXIwLnA4YmxsYXUubW9uZ29kYi5uZXQvP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eQ==
type: Opaque
